track_names_from_spreadsheet = [
    "LOW - Cazador death music",
    "SCL - Spooky forest",
    "END - Astarion evil ending BGM",
    'END - Dominated brain - "In my name"',
    'END - Dominated brain - "In my name"',
    "END - Final decision",
    "END - Final decision",
    "END - Final decision",
    "Act 2 - Resist Durge BGM",
    "Pre-Orin fight?",
    "???",
    "???",
    "???",
    "???",
    "The Power - Metal (Karlach in Avernus BGM)",
    "House of Hope battle music? alt Raphael's Final Act",
    "Hag swamp BGM",
    "Act 1 BGM",
    "Queen Vlaakith Talk Music",
    "Queen Vlaakith Talk Music 2",
    "Queen Vlaakith Talk Music 3",
    "I Want to Live - Classical",
    "I Want to Live - Classical",
]
